---
abstract: 'Render HTML representations of barcodes'
author:
  - 'Mark A. Stratman, C<< <stratman@gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Barcode
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.15
resources:
  homepage: http://github.com/mstratman/HTML-Barcode/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/mstratman/HTML-Barcode.git
    web: http://github.com/mstratman/HTML-Barcode/tree
version: 0.10
